# Numpy Library
NumPy is a python package for scientific computing. It provides multidimensional array objects and efficient operations 
on them.


Source: Cheat sheet - https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python

In [244]:
import numpy as np

## array

In [246]:
# let's first create a python list
my_list=[1,2,3,'Iresha', 4.5]
my_list

[1, 2, 3, 'Iresha', 4.5]

In [247]:
# Now let's covert this list to a Numpy array
array_1=np.array(my_list)
array_1

array(['1', '2', '3', 'Iresha', '4.5'], dtype='<U32')

In [248]:
#Creating a 2D-array
array_2d=np.array([(2,4,5),(6,5,1)])
array_2d

array([[2, 4, 5],
       [6, 5, 1]])

In [249]:
#Creating a 3D-array
array_3d=np.array([[(2,4,5), (6,5,1)], [(3,2,1),(7,8,9)]])
array_3d

array([[[2, 4, 5],
        [6, 5, 1]],

       [[3, 2, 1],
        [7, 8, 9]]])

## zeros and ones

In [251]:
# to create an array of zeroes
array_zeros=np.zeros((3,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [252]:
# to create an array of ones
# to have the ones dispalyed as integers, we need to specify dtype. If not the ones will be displayed as '1.'
array_ones=np.ones((2,4),dtype=np.int16)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

## arange

In [254]:
# creates an array of evenly spaced values (step value)
array=np.arange(-1,5)
array

array([-1,  0,  1,  2,  3,  4])

In [255]:
# To return a stepped sequence from start (inclusive) to the end (exclusive)
array=np.arange(1,8,2)
array

array([1, 3, 5, 7])

## linspace

In [257]:
# creates an array of evenly spaced values (number of samples)
array=np.linspace(0,2,9)
array

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## full

In [259]:
#creates a constant array
array = np.full((2,2,),7)
array

array([[7, 7],
       [7, 7]])

## eye

In [261]:
# creates identity matrix
array= np.eye(3, dtype=np.int16)
array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

## empty
This creates and array and the values can be anything that was in the memory location when the array was created. This is faster than creating arrays with ones and zeros, and is used in performance-sensitive situations and when you do not need to immediately initialize an array.

In [263]:
# creates an empty array
array=np.empty((3,2))
array

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 5.34041153e-307],
       [2.67019864e-306, 2.42092166e-322]])

## random

In [265]:
# creates an array with random values
array=np.random.random((1,4))
array

array([[0.10659758, 0.92852102, 0.9136193 , 0.79278825]])

## reshape

In [267]:
# let's first create a 2*3 array
a=np.array([(1,2,3), (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [268]:
# reshape method reshapes, but does not change data
# the first number within brackets is the number of rows we require
# -1 means that NumPy will automatically calculate this dimension based on the other dimensions and the total number of elements in the array.
b=a.reshape(2,-1)
b

array([[1, 2, 3],
       [4, 5, 6]])

## resize

In [270]:
a = np.array([(3,4,5), (9,5,2)])
a

array([[3, 4, 5],
       [9, 5, 2]])

In [271]:
# Modifies the original array in place, changing its shape and repeating the pattern to fill the array
c=np.resize(a,(1,8))
c

array([[3, 4, 5, 9, 5, 2, 3, 4]])

Note: a.resize((1,8)) did not work as resize() method cannot be used on arrays that are views or slices of other arrays.

## append
### Output as a 1-D array

In [274]:
a

array([[3, 4, 5],
       [9, 5, 2]])

In [275]:
b=np.array([(1,1,1)])
b

array([[1, 1, 1]])

In [276]:
# append two arrays
c = np.append(a,b)
c

array([3, 4, 5, 9, 5, 2, 1, 1, 1])

### Output as a 2-D array

In [278]:
a

array([[3, 4, 5],
       [9, 5, 2]])

In [279]:
b = np.array([(6,2,3),(7,1,2)])
b

array([[6, 2, 3],
       [7, 1, 2]])

In [280]:
# append two arrays and the output to be a 2-D array
c=np.append(a,b,axis=1)
c

array([[3, 4, 5, 6, 2, 3],
       [9, 5, 2, 7, 1, 2]])

## insert

In [282]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [283]:
#insert 10 at index 4 
b=np.insert(a,4,10)
b

array([ 1,  2,  3,  4, 10])

## concatenate

In [285]:
a

array([1, 2, 3, 4])

In [286]:
b

array([ 1,  2,  3,  4, 10])

In [287]:
# concatenating two arrays along the 0 axis
c=np.concatenate((a,b), axis=0)
c

array([ 1,  2,  3,  4,  1,  2,  3,  4, 10])